// <auto-generated />
using System;
using GlobalOrbitra.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlobalOrbitra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251002193811_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.ChainModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChainType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChainModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChainType = "EVM",
                            IsActive = true,
                            Name = "Ethereum",
                            RpcUrl = "https://mainnet.infura.io/v3/YOUR_PROJECT_ID",
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = 2,
                            ChainType = "TRON",
                            IsActive = true,
                            Name = "Tron",
                            RpcUrl = "https://api.trongrid.io",
                            Symbol = "TRX"
                        },
                        new
                        {
                            Id = 3,
                            ChainType = "EVM",
                            IsActive = true,
                            Name = "Binance Smart Chain",
                            RpcUrl = "https://bsc-dataseed.binance.org",
                            Symbol = "BSC"
                        },
                        new
                        {
                            Id = 4,
                            ChainType = "Solana",
                            IsActive = true,
                            Name = "Solana",
                            RpcUrl = "https://api.mainnet-beta.solana.com",
                            Symbol = "SOL"
                        });
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.TokenModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Chain")
                        .HasColumnType("int");

                    b.Property<int>("ChainId")
                        .HasColumnType("int");

                    b.Property<int?>("ChainModelId")
                        .HasColumnType("int");

                    b.Property<string>("ContractAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Decimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsToken")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChainModelId");

                    b.ToTable("TokenModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chain = 0,
                            ChainId = 1,
                            ContractAddress = "0x0000000000000000000000000000000000000000",
                            Decimal = 18m,
                            IsActive = true,
                            IsToken = false,
                            Name = "ETH",
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = 2,
                            Chain = 0,
                            ChainId = 2,
                            ContractAddress = "TRX_NATIVE",
                            Decimal = 6m,
                            IsActive = true,
                            IsToken = false,
                            Name = "TRX",
                            Symbol = "TRX"
                        },
                        new
                        {
                            Id = 3,
                            Chain = 0,
                            ChainId = 3,
                            ContractAddress = "BSC_NATIVE",
                            Decimal = 18m,
                            IsActive = true,
                            IsToken = false,
                            Name = "BSC",
                            Symbol = "BSC"
                        },
                        new
                        {
                            Id = 4,
                            Chain = 0,
                            ChainId = 4,
                            ContractAddress = "SOL_NATIVE",
                            Decimal = 9m,
                            IsActive = true,
                            IsToken = false,
                            Name = "SOL",
                            Symbol = "SOL"
                        });
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.TransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Commusion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AssetTransactionModels");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserModels");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.UserWalletModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("UserWalletModels");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.TokenModel", b =>
                {
                    b.HasOne("GlobalOrbitra.Models.UserModel.ChainModel", null)
                        .WithMany("TokenModels")
                        .HasForeignKey("ChainModelId");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.TransactionModel", b =>
                {
                    b.HasOne("GlobalOrbitra.Models.UserModel.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.UserWalletModel", b =>
                {
                    b.HasOne("GlobalOrbitra.Models.UserModel.TokenModel", "Token")
                        .WithMany("UserWallets")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalOrbitra.Models.UserModel.UserModel", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.ChainModel", b =>
                {
                    b.Navigation("TokenModels");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.TokenModel", b =>
                {
                    b.Navigation("UserWallets");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.UserModel", b =>
                {
                    b.Navigation("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
