// <auto-generated />
using System;
using GlobalOrbitra.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlobalOrbitra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.ChainModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChainType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChainModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChainType = "EVM",
                            IsActive = true,
                            Name = "Ethereum",
                            RpcUrl = "https://mainnet.infura.io/v3/YOUR_PROJECT_ID",
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = 2,
                            ChainType = "TRON",
                            IsActive = true,
                            Name = "Tron",
                            RpcUrl = "https://api.trongrid.io",
                            Symbol = "TRX"
                        },
                        new
                        {
                            Id = 3,
                            ChainType = "EVM",
                            IsActive = true,
                            Name = "Binance Smart Chain",
                            RpcUrl = "https://bsc-dataseed.binance.org",
                            Symbol = "BSC"
                        },
                        new
                        {
                            Id = 4,
                            ChainType = "Solana",
                            IsActive = true,
                            Name = "Solana",
                            RpcUrl = "https://api.mainnet-beta.solana.com",
                            Symbol = "SOL"
                        },
                        new
                        {
                            Id = 5,
                            ChainType = "TRON",
                            IsActive = true,
                            Name = "Tron Nile Testnet",
                            RpcUrl = "https://nile.trongrid.io",
                            Symbol = "TRX"
                        });
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.TokenModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChainId")
                        .HasColumnType("int");

                    b.Property<string>("ContractAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Decimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsToken")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChainId");

                    b.ToTable("TokenModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChainId = 1,
                            ContractAddress = "0x0000000000000000000000000000000000000000",
                            Decimal = 18m,
                            IsActive = true,
                            IsToken = false,
                            Name = "ETH",
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = 2,
                            ChainId = 2,
                            ContractAddress = "TRX_NATIVE",
                            Decimal = 6m,
                            IsActive = true,
                            IsToken = false,
                            Name = "TRX",
                            Symbol = "TRX"
                        },
                        new
                        {
                            Id = 3,
                            ChainId = 3,
                            ContractAddress = "BSC_NATIVE",
                            Decimal = 18m,
                            IsActive = true,
                            IsToken = false,
                            Name = "BSC",
                            Symbol = "BSC"
                        },
                        new
                        {
                            Id = 4,
                            ChainId = 4,
                            ContractAddress = "SOL_NATIVE",
                            Decimal = 9m,
                            IsActive = true,
                            IsToken = false,
                            Name = "SOL",
                            Symbol = "SOL"
                        },
                        new
                        {
                            Id = 5,
                            ChainId = 5,
                            ContractAddress = "TRX_NATIVE",
                            Decimal = 6m,
                            IsActive = true,
                            IsToken = false,
                            Name = "TRX (Testnet)",
                            Symbol = "TRX"
                        },
                        new
                        {
                            Id = 6,
                            ChainId = 5,
                            ContractAddress = "TXYZopYRdj2D9XRtbG411XZZ3kM5VkAeBf",
                            Decimal = 6m,
                            IsActive = true,
                            IsToken = true,
                            Name = "Tether USDT (Nile)",
                            Symbol = "USDT"
                        },
                        new
                        {
                            Id = 7,
                            ChainId = 5,
                            ContractAddress = "TEMVynQpntMqkPxP6wXTW2K7e4sM3cRmWz",
                            Decimal = 6m,
                            IsActive = true,
                            IsToken = true,
                            Name = "USD Coin (Nile)",
                            Symbol = "USDC"
                        },
                        new
                        {
                            Id = 8,
                            ChainId = 5,
                            ContractAddress = "TVSvjZdyDSNocHm7dP3jvCmMNsCnMTPa5W",
                            Decimal = 18m,
                            IsActive = true,
                            IsToken = true,
                            Name = "BTT (Nile)",
                            Symbol = "BTT"
                        },
                        new
                        {
                            Id = 9,
                            ChainId = 5,
                            ContractAddress = "TFT7sNiNDGZcqL7z7dwXUPpxrx1Ewk8iGL",
                            Decimal = 18m,
                            IsActive = true,
                            IsToken = true,
                            Name = "USDD Token (Nile)",
                            Symbol = "USDD"
                        });
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.TransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TokenId")
                        .HasColumnType("int");

                    b.Property<string>("TxHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("TransactionModel");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserModels");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.UserWalletModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("UserWalletModels");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.TokenModel", b =>
                {
                    b.HasOne("GlobalOrbitra.Models.UserModel.ChainModel", "Chain")
                        .WithMany("TokenModels")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chain");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.TransactionModel", b =>
                {
                    b.HasOne("GlobalOrbitra.Models.UserModel.TokenModel", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId");

                    b.HasOne("GlobalOrbitra.Models.UserModel.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.UserWalletModel", b =>
                {
                    b.HasOne("GlobalOrbitra.Models.UserModel.TokenModel", "Token")
                        .WithMany("UserWallets")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalOrbitra.Models.UserModel.UserModel", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.ChainModel", b =>
                {
                    b.Navigation("TokenModels");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.TokenModel", b =>
                {
                    b.Navigation("UserWallets");
                });

            modelBuilder.Entity("GlobalOrbitra.Models.UserModel.UserModel", b =>
                {
                    b.Navigation("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
